import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='bg-green-200 p-8 mb-7 flex justify-center items-center'>
          Header
        </header>
        {children}
        <footer className='bg-green-200 p-8 mt-7 flex justify-center items-center'>
          Footer
        </footer>
      </body>
    </html>
  )
}
